// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPByRE8aX8nJI81AzwMfIClAa4D4UICm8',
    appId: '1:81867038036:web:9c13a7a14416e6be697cc1',
    messagingSenderId: '81867038036',
    projectId: 'todolist-firebase-5773e',
    authDomain: 'todolist-firebase-5773e.firebaseapp.com',
    storageBucket: 'todolist-firebase-5773e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC889tihvzIhozN6OXD9wjCsQZ6qolRn3w',
    appId: '1:81867038036:android:18892e48d9f88fe9697cc1',
    messagingSenderId: '81867038036',
    projectId: 'todolist-firebase-5773e',
    storageBucket: 'todolist-firebase-5773e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyVmj27vXuqWpNfTvqatuwtcZHFFpSny4',
    appId: '1:81867038036:ios:f8bb84df9a2f8716697cc1',
    messagingSenderId: '81867038036',
    projectId: 'todolist-firebase-5773e',
    storageBucket: 'todolist-firebase-5773e.appspot.com',
    iosBundleId: 'com.example.flutter2110424',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyVmj27vXuqWpNfTvqatuwtcZHFFpSny4',
    appId: '1:81867038036:ios:f8bb84df9a2f8716697cc1',
    messagingSenderId: '81867038036',
    projectId: 'todolist-firebase-5773e',
    storageBucket: 'todolist-firebase-5773e.appspot.com',
    iosBundleId: 'com.example.flutter2110424',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPByRE8aX8nJI81AzwMfIClAa4D4UICm8',
    appId: '1:81867038036:web:ca7c875b33454489697cc1',
    messagingSenderId: '81867038036',
    projectId: 'todolist-firebase-5773e',
    authDomain: 'todolist-firebase-5773e.firebaseapp.com',
    storageBucket: 'todolist-firebase-5773e.appspot.com',
  );

}